FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install streamlit
RUN pip install streamlit plotly
RUN pip install streamlit logger
RUN pip install python-dotenv
RUN pip install openai

EXPOSE 8501

CMD ["streamlit", "run", "chat.py", "--server.address=0.0.0.0"]